# Minimal yazi config - no colors, just shapes

[manager]
ratio = [1,3,4]
show_hidden = false
sort_by = "mtime"
sort_dir_first = true
linemode = "mtime"
show_symlink = true

[preview]
max_width = 1200
max_height = 1200
wrap = "no"
image_delay = 10
